Added small check if instance exists to omd commands which affect a specific site

diff --git a/bin/omd b/bin/omd
--- a/bin/omd
+++ b/bin/omd
@@ -63,15 +63,24 @@ version_specific_omd ()
     exec /omd/versions/$VERSION/bin/omd "$@"
 }
 
+check_site ()
+{
+    if [ ! -d "/omd/sites/$1" ]; then
+        echo "Error: The specified site \"$1\" does not exist"
+        exit 1
+    fi
+}
 
 COMMAND=$1
 case "$COMMAND" in 
     rm|cp|mv)
         SITE="$2"
+				check_site "$SITE"
         exec /omd/sites/$SITE/bin/omd "$@"
     ;;
     start|stop|restart|reload|status)
         if [ "$2" ] ; then
+				    check_site "$2"
             echo "$2:"
             exec /omd/sites/$2/bin/omd "$@"
         else
