unify core rc scripts

diff --git a/packages/icinga/skel/etc/init.d/icinga b/packages/icinga/skel/etc/init.d/icinga
--- a/packages/icinga/skel/etc/init.d/icinga
+++ b/packages/icinga/skel/etc/init.d/icinga
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # chkconfig: 345 99 01
-# description: Icinga network monitoring daemon
+# description: icinga network monitoring daemon
 
 ### BEGIN INIT INFO
 # Provides:       icinga
@@ -9,7 +9,7 @@
 # Required-Stop:
 # Default-Start:  2 3 5
 # Default-Stop:
-# Description:    Icinga network monitoring daemon
+# Description:    icinga network monitoring daemon
 ### END INIT INFO
 
 # Author: Lars Michelsen <lm@mathias-kettner.de>
@@ -26,7 +26,8 @@
 # - There are exceptions for the exit code handling:
 #   - When a service is already stopped and should be
 #     restarted/stopped, it should result in an exit code of 0.
-#   - FIXME: What if a service should be started and is already started?
+#   - When a service is already running and should be started
+#     this also should result in an exit code of 0.
 # - When a restart is requested and the program is still not running
 #   the script should only execute a start
 # - When a restart is requested and the program can not be stopped the
@@ -40,58 +41,62 @@ cd ###ROOT###
 . etc/omd/site.conf
 [ "$CONFIG_CORE" = "icinga" ] || exit 5
 
-BIN=###ROOT###/bin/icinga
-CFG_FILE=###ROOT###/tmp/icinga/icinga.cfg
-STATUS_FILE=###ROOT###/tmp/icinga/status.dat
-CMD_FILE=###ROOT###/tmp/run/icinga.cmd
-PID_FILE=###ROOT###/tmp/lock/icinga.lock
-STATUS_DAT=###ROOT###/tmp/icinga/status.dat
+BIN=###ROOT###/bin/${CONFIG_CORE}
+CFG_FILE=###ROOT###/tmp/${CONFIG_CORE}/${CONFIG_CORE}.cfg
+STATUS_FILE=###ROOT###/tmp/${CONFIG_CORE}/status.dat
+CMD_FILE=###ROOT###/tmp/run/${CONFIG_CORE}.cmd
+PID_FILE=###ROOT###/tmp/lock/${CONFIG_CORE}.lock
+STATUS_DAT=###ROOT###/tmp/${CONFIG_CORE}/status.dat
 USR=###SITE###
 GRP=###SITE###
 
+# You can set the environment variable CORE_NOVERIFY=yes
+# in order to supress a verification of the core configuration
+# in case of start, restart or reload. This is in order to
+# avoid duplicate effort when being called by cmk -R or 
+# cmk -O.
+# export CORE_NOVERIFY=yes
+
+# Make sure that check plugins do not run localized.
+# check_icmp outputs performance data with german
+# comma instead of dot and makes it unparsable.
+unset LANG
+export LC_ALL=C
+
 # OMD: create configuration file out of fragments
 case "$1" in start|restart|reload|checkconfig|check)
-    ln -sfn $OMD_ROOT/tmp/icinga $OMD_ROOT/tmp/core
-    merge-icinga-config \
-       ###ROOT###/etc/icinga/icinga.d/*.cfg \
-       ###ROOT###/etc/icinga/icinga.cfg \
+    ln -sfn $OMD_ROOT/tmp/${CONFIG_CORE} $OMD_ROOT/tmp/core
+    rm -f $CFG_FILE
+    merge-core-config \
+       ###ROOT###/etc/${CONFIG_CORE}/${CONFIG_CORE}.d/*.cfg \
+       ###ROOT###/etc/${CONFIG_CORE}/${CONFIG_CORE}.cfg \
        > $CFG_FILE || rm -f $CFG_FILE
+    if [ $? -ne 0 ]; then exit 1; fi
        rm -f $OMD_ROOT/tmp/nagios/nagios.cfg
        ln -sfn $CFG_FILE $OMD_ROOT/tmp/nagios/nagios.cfg
-    if [ $? -ne 0 ]; then exit 1; fi
 esac
 
 OPTIONS="-ud"
 
-# Fetches the pid of the currently running nagios process of the given
+# Fetches the pid of the currently running core process of the given
 # user.
 #
 # --ppid 1 in ps seem not to filter by direct ppid but by the whole
 # parent process tree. So filter by hand again.
+#
+# Removed the filter "-P 1" (filters for ppid=1 processes) as on some
+# distros, like Ubuntu 13.10 and newer, the processes will not be childs
+# of PID 1, instead the process is child of an "upstart user session",
+# which is visible via ps as "init --user". This will be the PPID until
+# the user session ends, then the process will be moved to PPID=1.
+# Strange one, but we try to simply ignore that...  "-o" should make it.
 # 
 # It returns 1 when no process can be found and echos the PID while
 # returning 0 when a process can be found.
-nagios_proc() {
-    PROC=$(ps -u $USR --ppid 1 -o pid,ppid,cmd \
-             | grep "$BIN $OPTIONS $CFG_FILE" 2>&1 | grep ' 1 ' | grep -v grep)
-    PID=$(echo "$PROC" | sed 's/^ *//g' | cut -d' ' -f1)
-    if [ "$PID" != "" ]; then
-        echo "$PID"
-        return 0
-    else
-        return 1
-    fi
+pidof_core() {
+    pgrep -u $OMD_SITE -o -fx "$BIN $OPTIONS $CFG_FILE" 2>/dev/null
 }
 
-# First try to use the process list to gather a nagios process,
-# when no process is found via ps take a look at the lock file
-#
-# It returns 1 when no process can be found and echos the PID while
-# returning 0 when a process can be found.
-pidof_nagios() {
-    nagios_proc
-    return $?
-}
 
 verify_config() {
     if [ "$1" != "quiet" ]; then
@@ -106,7 +111,7 @@ verify_config() {
         return 0
     else
         if [ "$1" != "quiet" ]; then
-            echo "CONFIG ERROR! Aborted. Check your Icinga configuration."
+            echo "CONFIG ERROR! Aborted. Check your ${CONFIG_CORE} configuration."
         fi
         echo "$RESULT" >&2
         return 1
@@ -121,47 +126,52 @@ prep_start() {
     chown $USR:$GRP $PID_FILE
 }
 
-nagios_wait_stop() {
-    pid=$(pidof_nagios) || true
-    if ! kill -0 "${pid:-}" >/dev/null 2>&1; then
-        echo -n 'Not running. '
+core_wait_stop() {
+    pid=$(pidof_core) || {  
+        echo -n 'not running...' 
         return 0
-    fi
+    }
 
     # wait until really stopped.
-    # it might happen that nagios has a subprocess which
+    # it might happen that core has a subprocess which
     # is left running and becomes ppid 1 after killing the
-    # main nagios process. So fetch the process id again
+    # main core process. So fetch the process id again
     # multiple times to fetch new processes until all are gone.
-    if [ -n "${pid:-}" ]; then
-        I=0
-        while kill -0 ${pid:-} >/dev/null 2>&1; do
-            # Send single kill per process
-            kill $pid
-            while kill -0 ${pid:-} >/dev/null 2>&1;  do
-                if [ $I = '600' ]; then
-                    return 1
-                else
-                    [ $((I%5)) -eq 0 ] && echo -n "."
-                    I=$(($I+1))
-                    sleep 0.1
-                fi
-            done
-            # Is there another proc with ppid 1?
-            pid=$(pidof_nagios | head -n1) || true
-        done
-    fi
+    I=0
+    while kill -0 $pid >/dev/null 2>&1; do
+        # Send TERM to process group to kill the core process and also
+        # other processes started by this core process, for example
+        # check plugins which are currently running
+        kill -TERM -$pid
+        while kill -0 $pid  >/dev/null 2>&1;  do
+            if [ $I = '300' ]; then
+                # we likely have to kill core, so at least give the core 30 seconds to write the retention.dat
+                printf "[%lu] SAVE_STATE_INFORMATION;\n" `date +%s` > $OMD_ROOT/tmp/run/${CONFIG_CORE}.cmd
+            fi
+            if [ $I = '600' ]; then
+                echo -ne "\nsending SIGKILL"
+                kill -9 $pid
+            elif [ $I = '700' ]; then
+                return 1
+            fi
 
-    [ -f "$PID_FILE" ] && rm -f "$PID_FILE"
-    return 0
+            [ $((I%5)) -eq 0 ] && echo -n "."
+            I=$(($I+1))
+            sleep 0.1
+        done
+        # Is there another proc with ppid 1?
+        pid=$(pidof_core) || break
+    done
+
+    rm -f "$PID_FILE"
 }
 
-nagios_wait_start() {
+core_wait_start() {
     prep_start
     $BIN $OPTIONS $CFG_FILE
 
     I=0
-    while ! pidof_nagios >/dev/null 2>&1;  do
+    while ! pidof_core >/dev/null 2>&1;  do
         if [ $I = '10' ]; then
             return 1
         else
@@ -170,18 +180,16 @@ nagios_wait_start() {
             sleep 1
         fi
     done
-
-    return 0
 }
 
 if [ ! -f $BIN ]; then
-    echo "Icinga binary $BIN not found. Terminating..."
+    echo "${CONFIG_CORE} binary $BIN not found. Terminating..."
     exit 1
 fi
 
 case "$1" in start|restart|reload|checkconfig)
     if [ ! -f $CFG_FILE ]; then
-        echo "Icinga configuration file $CFG_FILE not found. Terminating..."
+        echo "${CONFIG_CORE} configuration file $CFG_FILE not found. Terminating..."
         exit 1
     fi
 esac
@@ -189,17 +197,15 @@ esac
 __init_hook $0 $1 pre
 case "$1" in
     start)
-         echo -n "Starting icinga..."
-         if pidof_nagios >/dev/null 2>&1; then
+         echo -n "Starting ${CONFIG_CORE}..."
+         if pidof_core >/dev/null 2>&1; then
              echo 'Already running.'
-             exit 1
+             exit 0
          fi
 
-         if ! verify_config quiet; then
-             exit 1
-         fi
+         [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
 
-         if nagios_wait_start; then
+         if core_wait_start; then
              echo 'OK'
              __init_hook $0 $1 post 0
              exit 0
@@ -210,8 +216,8 @@ case "$1" in
          fi
     ;;
     stop)
-        echo -n "Stopping icinga..."
-        if nagios_wait_stop; then
+        echo -n "Stopping ${CONFIG_CORE}..."
+        if core_wait_stop; then
             echo 'OK'
              __init_hook $0 $1 post 0
             exit 0
@@ -228,23 +234,20 @@ case "$1" in
         exit 0
     ;;
     status)
-        PID=$(pidof_nagios 2>&1) || true
-        if kill -0 "${PID:-}" >/dev/null 2>&1; then
-            echo "Running ($PID)."
-            exit 0
+        if pid=$(pidof_core 2>&1)
+        then
+            echo "Running ($pid)."
         else
-            echo 'Not running. '
+            echo 'Not running.'
             exit 1
         fi
     ;;
     restart)
-        if ! verify_config quiet; then
-            exit 1
-        fi
+        [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
 
-        $0 stop || (echo "Unable to stop icinga. Terminating..." && exit 1)
-        echo -n "Starting icinga..."
-        if nagios_wait_start; then
+        $0 stop || (echo "Unable to stop ${CONFIG_CORE}. Terminating..." && exit 1)
+        echo -n "Starting ${CONFIG_CORE}..."
+        if core_wait_start; then
             echo 'OK'
             exit 0
         else
@@ -254,18 +257,16 @@ case "$1" in
     ;;
 
     reload|force-reload)
-        if ! verify_config quiet; then
-            exit 1
-        fi
+        [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
 
-        # Execute a start when nagios is not running
-        if ! pidof_nagios >/dev/null 2>&1; then
+        # Execute a start when core is not running
+        if ! pid=$(pidof_core) 2>&1; then
             $0 start
             exit $?
         fi
 
-        echo -n "Reloading icinga configuration (PID: $PID)... "
-        if kill -HUP ${PID:-} >/dev/null 2>&1; then
+        echo -n "Reloading ${CONFIG_CORE} configuration (PID: $pid)... "
+        if kill -HUP $pid >/dev/null 2>&1; then
             echo 'OK'
             __init_hook $0 $1 post 0
             exit 0
@@ -276,7 +277,7 @@ case "$1" in
     ;;
 
     *)
-        echo "Usage: icinga {start|stop|restart|reload|status|checkconfig}"
+        echo "Usage: ${CONFIG_CORE} {start|stop|restart|reload|status|checkconfig}"
         exit 2
     ;;
 esac
diff --git a/packages/naemon/skel/etc/init.d/naemon b/packages/naemon/skel/etc/init.d/naemon
--- a/packages/naemon/skel/etc/init.d/naemon
+++ b/packages/naemon/skel/etc/init.d/naemon
@@ -25,7 +25,8 @@
 # - There are exceptions for the exit code handling:
 #   - When a service is already stopped and should be
 #     restarted/stopped, it should result in an exit code of 0.
-#   - FIXME: What if a service should be started and is already started?
+#   - When a service is already running and should be started
+#     this also should result in an exit code of 0.
 # - When a restart is requested and the program is still not running
 #   the script should only execute a start
 # - When a restart is requested and the program can not be stopped the
@@ -39,17 +40,17 @@ cd ###ROOT###
 . etc/omd/site.conf
 [ "$CONFIG_CORE" = "naemon" ] || exit 5
 
-BIN=###ROOT###/bin/naemon
-CFG_FILE=###ROOT###/tmp/naemon/naemon.cfg
-STATUS_FILE=###ROOT###/tmp/naemon/status.dat
-CMD_FILE=###ROOT###/tmp/run/naemon.cmd
-PID_FILE=###ROOT###/tmp/lock/naemon.lock
-STATUS_DAT=###ROOT###/tmp/naemon/status.dat
+BIN=###ROOT###/bin/${CONFIG_CORE}
+CFG_FILE=###ROOT###/tmp/${CONFIG_CORE}/${CONFIG_CORE}.cfg
+STATUS_FILE=###ROOT###/tmp/${CONFIG_CORE}/status.dat
+CMD_FILE=###ROOT###/tmp/run/${CONFIG_CORE}.cmd
+PID_FILE=###ROOT###/tmp/lock/${CONFIG_CORE}.lock
+STATUS_DAT=###ROOT###/tmp/${CONFIG_CORE}/status.dat
 USR=###SITE###
 GRP=###SITE###
 
 # You can set the environment variable CORE_NOVERIFY=yes
-# in order to supress a verification of the naemon configuration
+# in order to supress a verification of the core configuration
 # in case of start, restart or reload. This is in order to
 # avoid duplicate effort when being called by cmk -R or 
 # cmk -O.
@@ -63,18 +64,20 @@ export LC_ALL=C
 
 # OMD: create configuration file out of fragments
 case "$1" in start|restart|reload|checkconfig|check)
-    ln -sfn $OMD_ROOT/tmp/naemon $OMD_ROOT/tmp/core
-    merge-nagios-config \
-       ###ROOT###/etc/naemon/naemon.d/*.cfg \
-       ###ROOT###/etc/naemon/naemon.cfg \
+    ln -sfn $OMD_ROOT/tmp/${CONFIG_CORE} $OMD_ROOT/tmp/core
+    rm -f $CFG_FILE
+    merge-core-config \
+       ###ROOT###/etc/${CONFIG_CORE}/${CONFIG_CORE}.d/*.cfg \
+       ###ROOT###/etc/${CONFIG_CORE}/${CONFIG_CORE}.cfg \
        > $CFG_FILE || rm -f $CFG_FILE
+    if [ $? -ne 0 ]; then exit 1; fi
        rm -f $OMD_ROOT/tmp/nagios/nagios.cfg
        ln -sfn $CFG_FILE $OMD_ROOT/tmp/nagios/nagios.cfg
 esac
 
 OPTIONS="-ud"
 
-# Fetches the pid of the currently running naemon process of the given
+# Fetches the pid of the currently running core process of the given
 # user.
 #
 # --ppid 1 in ps seem not to filter by direct ppid but by the whole
@@ -89,7 +92,7 @@ OPTIONS="-ud"
 # 
 # It returns 1 when no process can be found and echos the PID while
 # returning 0 when a process can be found.
-pidof_naemon() {
+pidof_core() {
     pgrep -u $OMD_SITE -o -fx "$BIN $OPTIONS $CFG_FILE" 2>/dev/null
 }
 
@@ -102,14 +105,14 @@ verify_config() {
     if [ $? -eq 0 ]; then
         if [ "$1" != "quiet" ]; then
             echo "done."
-            echo "$RESULT"
+            echo "$RESULT" >&2
         fi
         return 0
     else
         if [ "$1" != "quiet" ]; then
-            echo "CONFIG ERROR! Aborted. Check your naemon configuration."
-            echo "$RESULT"
+            echo "CONFIG ERROR! Aborted. Check your ${CONFIG_CORE} configuration."
         fi
+        echo "$RESULT" >&2
         return 1
     fi
 }
@@ -122,27 +125,27 @@ prep_start() {
     chown $USR:$GRP $PID_FILE
 }
 
-naemon_wait_stop() {
-    pid=$(pidof_naemon) || {  
+core_wait_stop() {
+    pid=$(pidof_core) || {  
         echo -n 'not running...' 
         return 0
     }
 
     # wait until really stopped.
-    # it might happen that naemon has a subprocess which
+    # it might happen that core has a subprocess which
     # is left running and becomes ppid 1 after killing the
-    # main naemon process. So fetch the process id again
+    # main core process. So fetch the process id again
     # multiple times to fetch new processes until all are gone.
     I=0
     while kill -0 $pid >/dev/null 2>&1; do
-        # Send TERM to process group to kill the naemon process and also
-        # other processes started by this naemon process, for example
+        # Send TERM to process group to kill the core process and also
+        # other processes started by this core process, for example
         # check plugins which are currently running
         kill -TERM -$pid
         while kill -0 $pid  >/dev/null 2>&1;  do
             if [ $I = '300' ]; then
-                # we likely have to kill naemon, so at least give the core 30 seconds to write the retention.dat
-                printf "[%lu] SAVE_STATE_INFORMATION;\n" `date +%s` > $OMD_ROOT/tmp/run/naemon.cmd
+                # we likely have to kill core, so at least give the core 30 seconds to write the retention.dat
+                printf "[%lu] SAVE_STATE_INFORMATION;\n" `date +%s` > $OMD_ROOT/tmp/run/${CONFIG_CORE}.cmd
             fi
             if [ $I = '600' ]; then
                 echo -ne "\nsending SIGKILL"
@@ -156,18 +159,18 @@ naemon_wait_stop() {
             sleep 0.1
         done
         # Is there another proc with ppid 1?
-        pid=$(pidof_naemon) || break
+        pid=$(pidof_core) || break
     done
 
     rm -f "$PID_FILE"
 }
 
-naemon_wait_start() {
+core_wait_start() {
     prep_start
     $BIN $OPTIONS $CFG_FILE
 
     I=0
-    while ! pidof_naemon >/dev/null 2>&1;  do
+    while ! pidof_core >/dev/null 2>&1;  do
         if [ $I = '10' ]; then
             return 1
         else
@@ -179,13 +182,13 @@ naemon_wait_start() {
 }
 
 if [ ! -f $BIN ]; then
-    echo "naemon binary $BIN not found. Terminating..."
+    echo "${CONFIG_CORE} binary $BIN not found. Terminating..."
     exit 1
 fi
 
 case "$1" in start|restart|reload|checkconfig)
     if [ ! -f $CFG_FILE ]; then
-        echo "naemon configuration file $CFG_FILE not found. Terminating..."
+        echo "${CONFIG_CORE} configuration file $CFG_FILE not found. Terminating..."
         exit 1
     fi
 esac
@@ -193,15 +196,15 @@ esac
 __init_hook $0 $1 pre
 case "$1" in
     start)
-         echo -n "Starting naemon..."
-         if pidof_naemon >/dev/null 2>&1; then
+         echo -n "Starting ${CONFIG_CORE}..."
+         if pidof_core >/dev/null 2>&1; then
              echo 'Already running.'
-             exit 1
+             exit 0
          fi
 
          [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
 
-         if naemon_wait_start; then
+         if core_wait_start; then
              echo 'OK'
              __init_hook $0 $1 post 0
              exit 0
@@ -212,8 +215,8 @@ case "$1" in
          fi
     ;;
     stop)
-        echo -n "Stopping naemon..."
-        if naemon_wait_stop; then
+        echo -n "Stopping ${CONFIG_CORE}..."
+        if core_wait_stop; then
             echo 'OK'
              __init_hook $0 $1 post 0
             exit 0
@@ -230,7 +233,7 @@ case "$1" in
         exit 0
     ;;
     status)
-        if pid=$(pidof_naemon 2>&1)
+        if pid=$(pidof_core 2>&1)
         then
             echo "Running ($pid)."
         else
@@ -241,9 +244,9 @@ case "$1" in
     restart)
         [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
 
-        $0 stop || (echo "Unable to stop naemon. Terminating..." && exit 1)
-        echo -n "Starting naemon..."
-        if naemon_wait_start; then
+        $0 stop || (echo "Unable to stop ${CONFIG_CORE}. Terminating..." && exit 1)
+        echo -n "Starting ${CONFIG_CORE}..."
+        if core_wait_start; then
             echo 'OK'
             exit 0
         else
@@ -255,13 +258,13 @@ case "$1" in
     reload|force-reload)
         [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
 
-        # Execute a start when naemon is not running
-        if ! pid=$(pidof_naemon) 2>&1; then
+        # Execute a start when core is not running
+        if ! pid=$(pidof_core) 2>&1; then
             $0 start
             exit $?
         fi
 
-        echo -n "Reloading naemon configuration (PID: $pid)... "
+        echo -n "Reloading ${CONFIG_CORE} configuration (PID: $pid)... "
         if kill -HUP $pid >/dev/null 2>&1; then
             echo 'OK'
             __init_hook $0 $1 post 0
@@ -273,7 +276,7 @@ case "$1" in
     ;;
 
     *)
-        echo "Usage: naemon {start|stop|restart|reload|status|checkconfig}"
+        echo "Usage: ${CONFIG_CORE} {start|stop|restart|reload|status|checkconfig}"
         exit 2
     ;;
 esac
diff --git a/packages/nagios/skel/etc/init.d/nagios b/packages/nagios/skel/etc/init.d/nagios
--- a/packages/nagios/skel/etc/init.d/nagios
+++ b/packages/nagios/skel/etc/init.d/nagios
@@ -40,18 +40,18 @@ cd ###ROOT###
 . etc/omd/site.conf
 [ "$CONFIG_CORE" = "nagios" ] || exit 5
 
-BIN=###ROOT###/bin/nagios
-CFG_FILE=###ROOT###/tmp/nagios/nagios.cfg
-STATUS_FILE=###ROOT###/tmp/nagios/status.dat
-CMD_FILE=###ROOT###/tmp/run/nagios.cmd
-PID_FILE=###ROOT###/tmp/lock/nagios.lock
-STATUS_DAT=###ROOT###/tmp/nagios/status.dat
-CHECKRESULTS_DIR=###ROOT###/tmp/nagios/checkresults
+BIN=###ROOT###/bin/${CONFIG_CORE}
+CFG_FILE=###ROOT###/tmp/${CONFIG_CORE}/${CONFIG_CORE}.cfg
+STATUS_FILE=###ROOT###/tmp/${CONFIG_CORE}/status.dat
+CMD_FILE=###ROOT###/tmp/run/${CONFIG_CORE}.cmd
+PID_FILE=###ROOT###/tmp/lock/${CONFIG_CORE}.lock
+STATUS_DAT=###ROOT###/tmp/${CONFIG_CORE}/status.dat
+CHECKRESULTS_DIR=###ROOT###/tmp/${CONFIG_CORE}/checkresults
 USR=###SITE###
 GRP=###SITE###
 
 # You can set the environment variable CORE_NOVERIFY=yes
-# in order to supress a verification of the nagios configuration
+# in order to supress a verification of the core configuration
 # in case of start, restart or reload. This is in order to
 # avoid duplicate effort when being called by cmk -R or 
 # cmk -O.
@@ -65,18 +65,18 @@ export LC_ALL=C
 
 # OMD: create configuration file out of fragments
 case "$1" in start|restart|reload|checkconfig|check)
-    ln -sfn $OMD_ROOT/tmp/nagios $OMD_ROOT/tmp/core
+    ln -sfn $OMD_ROOT/tmp/${CONFIG_CORE} $OMD_ROOT/tmp/core
     rm -f $CFG_FILE
-    merge-nagios-config \
-       ###ROOT###/etc/nagios/nagios.d/*.cfg \
-       ###ROOT###/etc/nagios/nagios.cfg \
+    merge-core-config \
+       ###ROOT###/etc/${CONFIG_CORE}/${CONFIG_CORE}.d/*.cfg \
+       ###ROOT###/etc/${CONFIG_CORE}/${CONFIG_CORE}.cfg \
        > $CFG_FILE || rm -f $CFG_FILE
     if [ $? -ne 0 ]; then exit 1; fi
 esac
 
 OPTIONS="-ud"
 
-# Fetches the pid of the currently running nagios process of the given
+# Fetches the pid of the currently running core process of the given
 # user.
 #
 # --ppid 1 in ps seem not to filter by direct ppid but by the whole
@@ -91,7 +91,7 @@ OPTIONS="-ud"
 # 
 # It returns 1 when no process can be found and echos the PID while
 # returning 0 when a process can be found.
-pidof_nagios() {
+pidof_core() {
     pgrep -u $OMD_SITE -o -fx "$BIN $OPTIONS $CFG_FILE" 2>/dev/null
 }
 
@@ -109,7 +109,7 @@ verify_config() {
         return 0
     else
         if [ "$1" != "quiet" ]; then
-            echo "CONFIG ERROR! Aborted. Check your Nagios configuration."
+            echo "CONFIG ERROR! Aborted. Check your ${CONFIG_CORE} configuration."
         fi
         echo "$RESULT" >&2
         return 1
@@ -125,48 +125,52 @@ prep_start() {
     rm -f $CHECKRESULTS_DIR/*
 }
 
-nagios_wait_stop() {
-    pid=$(pidof_nagios) || {  
+core_wait_stop() {
+    pid=$(pidof_core) || {  
         echo -n 'not running...' 
         return 0
     }
 
     # wait until really stopped.
-    # it might happen that nagios has a subprocess which
+    # it might happen that core has a subprocess which
     # is left running and becomes ppid 1 after killing the
-    # main nagios process. So fetch the process id again
+    # main core process. So fetch the process id again
     # multiple times to fetch new processes until all are gone.
     I=0
     while kill -0 $pid >/dev/null 2>&1; do
-        # Send TERM to process group to kill the nagios process and also
-        # other processes started by this nagios process, for example
+        # Send TERM to process group to kill the core process and also
+        # other processes started by this core process, for example
         # check plugins which are currently running
         kill -TERM -$pid
         while kill -0 $pid  >/dev/null 2>&1;  do
+            if [ $I = '300' ]; then
+                # we likely have to kill core, so at least give the core 30 seconds to write the retention.dat
+                printf "[%lu] SAVE_STATE_INFORMATION;\n" `date +%s` > $OMD_ROOT/tmp/run/${CONFIG_CORE}.cmd
+            fi
             if [ $I = '600' ]; then
                 echo -ne "\nsending SIGKILL"
                 kill -9 $pid
             elif [ $I = '700' ]; then
-                return 1 
+                return 1
             fi
-                
+
             [ $((I%5)) -eq 0 ] && echo -n "."
             I=$(($I+1))
             sleep 0.1
         done
         # Is there another proc with ppid 1?
-        pid=$(pidof_nagios) || break
+        pid=$(pidof_core) || break
     done
-    
+
     rm -f "$PID_FILE"
 }
 
-nagios_wait_start() {
+core_wait_start() {
     prep_start
     $BIN $OPTIONS $CFG_FILE
 
     I=0
-    while ! pidof_nagios >/dev/null 2>&1;  do
+    while ! pidof_core >/dev/null 2>&1;  do
         if [ $I = '10' ]; then
             return 1
         else
@@ -178,13 +182,13 @@ nagios_wait_start() {
 }
 
 if [ ! -f $BIN ]; then
-    echo "Nagios binary $BIN not found. Terminating..."
+    echo "${CONFIG_CORE} binary $BIN not found. Terminating..."
     exit 1
 fi
 
 case "$1" in start|restart|reload|checkconfig)
     if [ ! -f $CFG_FILE ]; then
-        echo "Nagios configuration file $CFG_FILE not found. Terminating..."
+        echo "${CONFIG_CORE} configuration file $CFG_FILE not found. Terminating..."
         exit 1
     fi
 esac
@@ -192,15 +196,15 @@ esac
 __init_hook $0 $1 pre
 case "$1" in
     start)
-         echo -n "Starting nagios..."
-         if pidof_nagios >/dev/null 2>&1; then
+         echo -n "Starting ${CONFIG_CORE}..."
+         if pidof_core >/dev/null 2>&1; then
              echo 'Already running.'
              exit 0
          fi
 
          [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
 
-         if nagios_wait_start; then
+         if core_wait_start; then
              echo 'OK'
              __init_hook $0 $1 post 0
              exit 0
@@ -211,8 +215,8 @@ case "$1" in
          fi
     ;;
     stop)
-        echo -n "Stopping nagios..."
-        if nagios_wait_stop; then
+        echo -n "Stopping ${CONFIG_CORE}..."
+        if core_wait_stop; then
             echo 'OK'
              __init_hook $0 $1 post 0
             exit 0
@@ -229,7 +233,7 @@ case "$1" in
         exit 0
     ;;
     status)
-        if pid=$(pidof_nagios 2>&1)
+        if pid=$(pidof_core 2>&1)
         then
             echo "Running ($pid)."
         else
@@ -240,9 +244,9 @@ case "$1" in
     restart)
         [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
 
-        $0 stop || (echo "Unable to stop nagios. Terminating..." && exit 1)
-        echo -n "Starting nagios..."
-        if nagios_wait_start; then
+        $0 stop || (echo "Unable to stop ${CONFIG_CORE}. Terminating..." && exit 1)
+        echo -n "Starting ${CONFIG_CORE}..."
+        if core_wait_start; then
             echo 'OK'
             exit 0
         else
@@ -250,17 +254,17 @@ case "$1" in
             exit 1
         fi
     ;;
-    
+
     reload|force-reload)
         [ "$CORE_NOVERIFY" ] || verify_config quiet || exit 1
-        
-        # Execute a start when nagios is not running
-        if ! pid=$(pidof_nagios) 2>&1; then
+
+        # Execute a start when core is not running
+        if ! pid=$(pidof_core) 2>&1; then
             $0 start
             exit $?
         fi
 
-        echo -n "Reloading nagios configuration (PID: $pid)... "
+        echo -n "Reloading ${CONFIG_CORE} configuration (PID: $pid)... "
         if kill -HUP $pid >/dev/null 2>&1; then
             echo 'OK'
             __init_hook $0 $1 post 0
@@ -272,9 +276,9 @@ case "$1" in
     ;;
 
     *)
-        echo "Usage: nagios {start|stop|restart|reload|status|checkconfig}"
+        echo "Usage: ${CONFIG_CORE} {start|stop|restart|reload|status|checkconfig}"
         exit 2
     ;;
 esac
- 
+
 # EOF
