omd: cleanup init scripts
  - try to avoid ###ROOT### and ###SITE### as they tend to cause conflicts, better use env variables
  - add meta info block to be interpreted by omd so it can faster decide if init script is used or not
  - add generic init functions to make init scripts shorter and use more shared code

diff --git a/packages/apache-omd/skel/etc/init.d/apache b/packages/apache-omd/skel/etc/init.d/apache
--- a/packages/apache-omd/skel/etc/init.d/apache
+++ b/packages/apache-omd/skel/etc/init.d/apache
@@ -1,14 +1,19 @@
 #!/bin/bash
 
-cd ###ROOT###
-. .profile
-. lib/omd/init_profile
+### OMD INIT INFO
+# PIDFILE:  tmp/run/apache.pid
+# DEPENDS:  CONFIG_APACHE_MODE != none
+# BINARY:   ###APACHE_BIN###
+# ARGMATCH: etc/apache/apache.conf
+### END INIT INFO
+
+cd || exit 1
 . etc/omd/site.conf
 if [ "$CONFIG_APACHE_MODE" == none ]; then
   exit 5
 fi
-
-. "$OMD_ROOT/.profile"
+. .profile
+. lib/omd/init_profile
 
 # Start httpd in the C locale by default.
 HTTPD_LANG="C"
@@ -17,155 +22,46 @@ HTTPD_LANG="C"
 # mod_ssl needs a pass-phrase from the user.
 INITLOG_ARGS=""
 
-APACHE_RUN_USER="###SITE###"
-APACHE_RUN_GROUP="###SITE###"
+NAME="apache"
+DAEMON="###APACHE_BIN###"
+PID_FILE=$OMD_ROOT/tmp/run/apache.pid
+OPTS="-f $OMD_ROOT/etc/apache/apache.conf"
+STOP_TIMEOUT=15
+STOP_CALLBACK="kill_stale_php_cgis"
 
-APACHE_BIN="###APACHE_BIN###"
-PID_FILE=###ROOT###/tmp/apache/run/apache.pid
-CONFIG_FILE=###ROOT###/etc/apache/apache.conf
+mkdir -p $OMD_ROOT/var/log/apache
 
-pidof_apache() {
-  # if there is actually an apache2 process whose pid is in PIDFILE,
-  # print it and return 0.
-  if [ -e "$PID_FILE" ]; then
-    PID=$(cat "$PID_FILE")
-    if kill -0 $PID >/dev/null 2>&1; then
-      echo $PID
-      return 0
-    fi
-  else
-    # It might happen that there is no pidfile but a process is running
-    # As fallback check the process table for the oldest apache process
-    # running as this user
-    PID=$(pgrep -u $OMD_SITE -o -f $APACHE_BIN)
-    if [ -n "$PID" ]; then
-        echo $PID
-        return 0
-    fi
-  fi
-  return 1
-}
-
-apache_wait_stop() {
-  # running ?
-  pid=$(pidof_apache) || true
-  if [ -n "${pid:-}" ]; then
-    kill ${pid:-}
-  else
-    echo -n '(not running)...'
-    return 0
-  fi
-
-  # wait until really stopped
-  if [ -n "${pid:-}" ]; then
-    i=0
-    while kill -0 "${pid:-}" 2> /dev/null;  do
-      if [ $i = '120' ]; then
-        kill_stale_php_cgis
-        return 1
-      else
-        echo -n "."
-        i=$(($i+1))
-        sleep 0.1
-      fi
-     done
-  fi
-  
-  [ -f "$PID_FILE" ] && rm -f "$PID_FILE"
-  kill_stale_php_cgis
-  return 0
-}
-
-apache_wait_start() {
-  if pidof_apache >/dev/null 2>&1; then
-    echo -n '(already running)...'
-    return 0
-  fi
-
-  mkdir -p ###ROOT###/tmp/apache/run
-  mkdir -p ###ROOT###/var/log/apache
-
+case "$1" in start|restart|reload)
   # (nearly) reproducible problems with apache at boot-time. (alloc_listener: failed to set up sockaddr for 127.0.0.1)
   # With this ping the problem disappears.
   test -f /etc/debian_version && test $(cut -f1 -d" " /proc/uptime | cut -f1 -d".") -lt 300 && ping -nqc 10 $CONFIG_APACHE_TCP_ADDR >/dev/null 2>&1
-  $APACHE_BIN -f "$CONFIG_FILE"
-  
-  i=0
-  while ! pidof_apache >/dev/null 2>&1;  do
-    if [ $i = '10' ]; then
-      return 1
-    else
-      echo -n "."
-      i=$(($i+1))
-      sleep 0.1
-    fi
-  done
+esac
 
+kill_stale_php_cgis() {
+  local COUNTER=$1
+  if [ $COUNTER -ne 50 ]; then
+    return
+  fi
+  i=1
+  pkill -u $OMD_SITE -f ###PHP_FCGI_BIN### >/dev/null 2>&1
+  while pkill -u $OMD_SITE -f ###PHP_FCGI_BIN### >/dev/null 2>&1
+  do
+    i=$((i+1))
+    if [ $i -gt 50 ] ; then
+        return
+    fi
+    sleep 0.1
+  done
+}
+
+# override generic reload function
+__generic_init_reload() {
+  if ! $DAEMON $OPTS -k graceful; then
+    echo "ERROR: failed to send SIGHUP"
+    return 1
+  fi
+  echo "OK"
   return 0
 }
 
-kill_stale_php_cgis() 
-{
-    i=1
-    killall -e ###PHP_FCGI_BIN### -u ###SITE### >/dev/null 2>&1 
-    while killall -e ###PHP_FCGI_BIN### -u ###SITE### >/dev/null 2>&1
-    do
-        i=$((i+1))
-        if [ $i -gt 50 ] ; then 
-            return
-        fi
-        sleep 0.1
-    done
-}
-
-__init_hook $0 $1 pre
-case $1 in
-  start)
-    echo -n "Starting dedicated Apache for site ###SITE###..."
-    if apache_wait_start; then
-      __init_hook $0 $1 post 0
-      echo 'OK'
-      exit 0
-    else
-      __init_hook $0 $1 post 1
-      echo 'ERROR'
-      exit 1
-    fi
-  ;;
-  stop)
-    echo -n "Stopping dedicated Apache for site ###SITE###..."
-    if apache_wait_stop; then
-      __init_hook $0 $1 post 0
-      echo 'OK'
-      exit 0
-    else
-      __init_hook $0 $1 post 1
-      echo 'ERROR'
-      exit 1
-    fi
-  ;;
-  restart)
-    $0 stop
-    $0 start
-  ;;
-  reload)
-    echo "Reloading dedicated Apache for site ###SITE###"
-    $APACHE_BIN -f "$CONFIG_FILE" -k graceful
-    __init_hook $0 $1 post $?
-  ;;
-  status)
-    PID=$(pidof_apache) || true
-    if [ -n "$PID" ]; then
-      echo "Apache is running (pid $PID)."
-      exit 0
-    else
-      echo "Apache is NOT running."
-      exit 1
-    fi
-  ;;
-  check)
-  ;;
-  *)
-    echo "Usage: $0 {start|stop|restart|reload|status}"
-  ;;
-esac
+__generic_init "$*"
diff --git a/packages/grafana-loki/skel/etc/init.d/promtail b/packages/grafana-loki/skel/etc/init.d/promtail
--- a/packages/grafana-loki/skel/etc/init.d/promtail
+++ b/packages/grafana-loki/skel/etc/init.d/promtail
@@ -1,31 +1,37 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-# description: Grafana promtail agent
+### OMD INIT INFO
+# PIDFILE:  tmp/run/promtail.pid
+# DEPENDS:  CONFIG_LOKI_PROMTAIL = on
+# BINARY:   bin/promtail
+# ARGMATCH: tmp/promtail.yaml
+### END INIT INFO
 
-# Check if grafana-loki-promtail is enabled in OMD. If not terminate.
-. lib/omd/init_profile
+cd || exit 1
 . etc/omd/site.conf
 if [ "$CONFIG_LOKI_PROMTAIL" != "on" ] ; then
     exit 5
 fi
+. lib/omd/init_profile
 
 NAME="Promtail"
 CONF_DIR=$OMD_ROOT/etc/loki
 LOG_DIR=$OMD_ROOT/var/log
 DATA_DIR=$OMD_ROOT/var/loki
 CONF_SRC=$CONF_DIR/promtail.yaml
-PID_FILE=$OMD_ROOT/tmp/run/$NAME.pid
-LOGFILE=$LOG_DIR/promtail.log
+PID_FILE=$OMD_ROOT/tmp/run/promtail.pid
+LOG_FILE=$LOG_DIR/promtail.log
 DAEMON=$OMD_ROOT/bin/promtail
 CFG_FILE=$OMD_ROOT/tmp/promtail.yaml
+OPTS="-config.expand-env=true -client.external-labels=instance=$(hostname) -config.file=${CFG_FILE}"
+NOHUP=1
+STORE_PID=1
+STOP_TIMEOUT=30
 
-OPTIONS="-config.expand-env=true -client.external-labels=instance=$(hostname) -config.file=${CFG_FILE}"
+mkdir -p "$LOG_DIR" "$DATA_DIR"
 
 # Put together fragments and build a new promtail.yaml
-#
-#
 rebuild_config() {
-    # 
     cat $CONF_SRC |\
         sed -n '1,/# - start of scrape configs/p' > $CFG_FILE
     for scrapes in $CONF_DIR/promtail.d/scrape_configs/*.yaml
@@ -37,98 +43,12 @@ rebuild_config() {
         sed -n '/# - end of scrape configs/,$p' >> $CFG_FILE
 }
 
-
-get_status() {
-    pid=$( cat $PID_FILE 2>/dev/null )
-    if [ -n "$pid" ]; then
-        if ps -p $pid > /dev/null 2>&1 ; then
-            echo "$NAME is running with pid $pid"
-            return 0;
-        fi
-    fi
-    echo "$NAME is not running"
-    return 1;
-}
-
-stop_promtail() {
-    pid=$( cat $PID_FILE 2>/dev/null )
-    if [ -z "$pid" ]; then
-        echo ". Not running."
-    else
-        ps -p $pid > /dev/null 2>&1 && kill $pid
-        for x in $(seq 15); do
-            printf "."
-            ps -p $pid > /dev/null 2>&1 || break
-            sleep 0.2;
-        done
-        if ! ps -p $pid > /dev/null 2>&1 ; then
-            echo "OK"
-            __init_hook $0 $1 post 0
-            exit 0;
-        else
-            echo "failed"
-            __init_hook $0 $1 post 1
-            exit 1;
-        fi
-    fi
-}
-
-__init_hook $0 $1 pre
-# OMD: create configuration file out of fragments
 case "$1" in start|restart|reload)
     rebuild_config
     if [ ! -f $CFG_FILE ]; then
-        echo "Prometheus configuration file $CFG_FILE not found. Terminating..."
+        echo "${NAME} configuration file $CFG_FILE not found. Terminating..."
         exit 1
     fi
 esac
-case "$1" in
-  start)
-        printf '%s' "Starting $NAME..."
 
-        if get_status > /dev/null ; then
-            echo "failed"
-            echo "$NAME already running"
-            exit 0;
-        fi
-
-        mkdir -p "$LOG_DIR" "$DATA_DIR"
-        touch "$PID_FILE"
-        ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.18 nohup $DAEMON $OPTIONS >>$LOGFILE 2>&1 &
-        if [ $? -eq 0 ]; then
-            echo "OK"
-            echo "$!" > $PID_FILE
-            __init_hook $0 $1 post 0
-            exit 0;
-        else
-            echo "failed"
-            __init_hook $0 $1 post 1
-            exit 1;
-        fi
-    ;;
-  stop)
-        printf '%s' "Stopping $NAME..."
-        pid=$( cat $PID_FILE 2>/dev/null )
-        if [ -z "$pid" ]; then
-            echo ". Not running."
-        else
-            stop_promtail;
-        fi
-    ;;
-  status)
-        get_status;
-        exit $?;
-    ;;
-    reload|restart)
-        $0 stop && sleep 1 && $0 start
-        exit $?
-    ;;
-  check)
-    ;;
-  *)
-        echo "Usage: $NAME {start|stop|kill|status|restart}"
-        exit 1
-    ;;
-esac
-
-exit 0
+__generic_init "$*"
diff --git a/packages/maintenance/skel/etc/init.d/crontab b/packages/maintenance/skel/etc/init.d/crontab
--- a/packages/maintenance/skel/etc/init.d/crontab
+++ b/packages/maintenance/skel/etc/init.d/crontab
@@ -1,39 +1,35 @@
 #!/bin/bash
-# 
-# Start only if Crontab is enabled
-. ###ROOT###/etc/omd/site.conf
+
+### OMD INIT INFO
+# DEPENDS:  CONFIG_CRONTAB = on
+### END INIT INFO
+
+cd || exit 1
+. etc/omd/site.conf
 if [ "$CONFIG_CRONTAB" != on ] ; then
     exit 5
 fi
+. lib/omd/init_profile
 
 NAME="crontab"
-MERGECRONTABS="###ROOT###/bin/merge-crontabs"
-CROND="###ROOT###/etc/cron.d/*[^~]"
-CRONTAB=`which crontab`          
+MERGECRONTABS="$OMD_ROOT/bin/merge-crontabs"
+CROND="$OMD_ROOT/etc/cron.d/*[^~]"
+CRONTAB=`which crontab`
 CRONTAB_OPTS=""
-USER="###SITE###"
 
-# check for root
-if [ $(id -un) != "$USER" ]; then
-    echo "must be run as site user"
-	exit 1
-fi
-
-# See how we were called.
+__init_hook $0 $1 pre
 case "$1" in
-
     start)
-	echo -en "Initializing Crontab..."
-	${MERGECRONTABS} ${CROND} | $CRONTAB $CRONTAB_OPTS - > /dev/null
+        echo -en "Initializing Crontab..."
+        ${MERGECRONTABS} ${CROND} | $CRONTAB $CRONTAB_OPTS - > /dev/null
         if [ $? -eq 0 ]; then
             echo "OK"
             exit 0
-	else
-	    echo "ERROR"
-	    exit 1
+        else
+            echo "ERROR"
+            exit 1
         fi
-        ;;
-
+    ;;
     stop)
         echo -n "Removing Crontab..."
         $CRONTAB $CRONTAB_OPTS -l >/dev/null 2>&1
@@ -44,12 +40,11 @@ case "$1" in
         fi
         echo OK
         exit 0
-        ;;
-
+    ;;
     restart|reload)
         $0 stop
         $0 start
-        ;;
+    ;;
     status)
         $CRONTAB $CRONTAB_OPTS -l >/dev/null 2>&1
         if [ $? -eq 0 ]; then
@@ -59,14 +54,11 @@ case "$1" in
             echo "crontab is empty"
             exit 1
         fi
-        ;;
+    ;;
     check)
         ;;
     *)
         echo "Usage: crontab {start|stop|restart|reload|status}"
         exit 1
-        ;;
-
+    ;;
 esac
-  
-# End of this script
