fix nsca reload: kill -HUP

diff --git a/packages/nsca/skel/etc/init.d/nsca b/packages/nsca/skel/etc/init.d/nsca
--- a/packages/nsca/skel/etc/init.d/nsca
+++ b/packages/nsca/skel/etc/init.d/nsca
@@ -48,7 +48,7 @@ stop)
 ;;
 reload|force-reload)
 	echo -n "Reloading $DESC: "
-	kill --signal HUP $(cat $PIDFILE) || die "ERROR: could not reload $NAME."
+	kill -HUP $(cat $PIDFILE) || die "ERROR: could not reload $NAME."
 	echo "$NAME."
     exit 0
 ;;
