omd: improve warning from port_is_used

diff --git a/packages/omd/port_is_used b/packages/omd/port_is_used
--- a/packages/omd/port_is_used
+++ b/packages/omd/port_is_used
@@ -13,14 +13,25 @@ port_is_used () {
         fi
         conf="/omd/sites/$S/etc/omd/site.conf"
         if [ "${S}" = "${OMD_SITE}" ]; then
+            # grep for port in other settings of same site
             if env | grep '^CONFIG_' | grep -F -v "CONFIG_${KEY}" | grep -E -q "=${PORT}\$|:${PORT}\$"; then
                 return 0
             fi
         else
+            if [ ! -r "/omd/sites/$S" ]; then
+                # no permission to read the site folder
+                echo "ERROR: Failed to read config of site ${S}. ${KEY} port will possibly be allocated twice" >&2
+                continue
+            fi
+            if [ ! -e "/omd/sites/$S/version" ]; then
+                # empty site -> no problem
+                continue
+            fi
             if ! test -r "$conf" ; then
                 echo "ERROR: Failed to read config of site ${S}. ${KEY} port will possibly be allocated twice" >&2
                 continue
             fi
+            # grep for port in other sites
             if grep -v '^#' < "$conf" | grep -E -q "='${PORT}'|:${PORT}'" ; then
                 return 0
             fi
