mysql: moved mysql_install_db from hook to init script
 - skip mysql checks on Ubuntu
 - add proper error for init script

diff --git a/packages/mysql-omd/skel/etc/init.d/mysql b/packages/mysql-omd/skel/etc/init.d/mysql
--- a/packages/mysql-omd/skel/etc/init.d/mysql
+++ b/packages/mysql-omd/skel/etc/init.d/mysql
@@ -77,9 +77,22 @@ mysql_wait_stop() {
     return 0
 }
 
+check_install_db() {
+    if [ ! -e ~/var/mysql/mysql ] ; then
+        echo "first start of mysql, creating initial database..."
+        mysql_install_db > $OMD_ROOT/var/log/omd.log 2>&1
+        if [ $? != 0 ]; then
+            echo "failed, please have a look at $OMD_ROOT/var/log/omd.log"
+            echo "or http://omdistro.org/wiki/omd/FAQ"
+            exit 1
+        fi
+    fi
+}
+
 case $1 in 
     start)
         echo -n "Starting MySQL... "
+        check_install_db;
         if mysql_wait_start; then
             echo 'OK.'
             exit 0
