ubuntu24.04: use newer python modules

diff --git a/packages/python-modules/Makefile b/packages/python-modules/Makefile
--- a/packages/python-modules/Makefile
+++ b/packages/python-modules/Makefile
@@ -15,6 +15,15 @@ WHEELSDIR=$(shell pwd)/wheels
 
 PIP=python3 -m pip
 
+HAS_PYTHON_312_OR_NEWER := $(shell \
+    required_version="3.12.0"; \
+    if [ $$(echo -e "$(PYTHON_V)\n$$required_version" | sort -V | head -n1) = "$$required_version" ]; then \
+        echo "true"; \
+    else \
+        echo "false"; \
+    fi \
+)
+
 # install toolchain required to build wheels
 BASE =
 BASE += setuptools-59.6.0.tar.gz
@@ -99,12 +108,19 @@ MODULES += omdeventhandler-1.1.0.1-py3-none-any.whl
 MODULES += monplugin-0.6.2.tar.gz                    # check_vsphere
 MODULES += checkvsphere-0.3.11.tar.gz
 
-# pywbem?
-#MODULES += nocaselist-1.0.6.tar.gz                   # pywbem-1.5.0
-#MODULES += nocasedict-1.0.4.tar.gz                   # pywbem-1.5.0
-#MODULES += yamlloader-1.2.2.tar.gz                   # pywbem-1.5.0
-#MODULES += pywbem-1.5.0.tar.gz
+# override some module for python 3.12, list could be reevaluated once rhel7 support got removed
+OVERRIDES=""
+ifeq ($(HAS_PYTHON_312_OR_NEWER),true)
+OVERRIDES += setuptools-70.3.0.tar.gz
+OVERRIDES += wheel-0.44.0.tar.gz
+OVERRIDES += pip-23.3.2.tar.gz
 
+OVERRIDES += setuptools_scm-8.1.0.tar.gz
+OVERRIDES += setuptools_rust-1.10.2.tar.gz
+OVERRIDES += cython-3.0.11.tar.gz
+OVERRIDES += pyyaml-6.0.2.tar.gz
+OVERRIDES += pymssql-2.3.1.tar.gz
+endif
 
 build:
 	mkdir -p wheels
@@ -115,13 +131,21 @@ build:
 	export ftp_proxy=http://external_dependencies_must_be_included_in_omd; \
 	export CFLAGS="-std=c99"; \
 	set -e ; \
+	shopt -s nocaseglob; \
 	for M in $(BASE); do \
-		MBASE=$$(echo $$M | sed -E -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/-/\*/g') ; \
+		MBASE=$$(echo $$M | sed -E -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/-(py2\.)*py3-.*whl//g' -e 's/-/\*/g') ; \
 		WHEEL=$$(ls $(WHEELSDIR)/$${MBASE}-* 2>/dev/null | head -1) ; \
 		[[ -n "$$WHEEL" ]] && [[ -f "$$WHEEL" ]] && continue ; \
+		for O in $(OVERRIDES); do \
+			if [[ $$O =~ $$(echo $${MBASE%%\**} | tr A-Z a-z)- ]]; then \
+				echo "using $$O instead of $$M"; \
+				M="$$O"; \
+				MBASE=$$(echo $$M | sed -E -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/-(py2\.)*py3-.*whl//g' -e 's/-/\*/g') ; \
+			fi; \
+		done; \
 		( \
 			cd src && \
-			( tar zxvf $$M || : ) && \
+			( tar zxf $$M --no-same-owner || : ) && \
 			cd ./$$MBASE/ && \
 			python3 setup.py bdist_wheel; \
 		); \
@@ -136,6 +160,13 @@ build:
 		SWHEEL=$$(ls src/$${MBASE}-* 2>/dev/null | head -1 | sed -e 's/^src.//g') ; \
 		echo "** $$M **" ; \
 		[[ -n "$$WHEEL" ]] && [[ -f "$$WHEEL" ]] && continue ; \
+		for O in $(OVERRIDES); do \
+			if [[ $$O =~ $$(echo $${MBASE%%\**} | tr A-Z a-z)- ]]; then \
+				echo "using $$O instead of $$M"; \
+				M="$$O"; \
+				MBASE=$$(echo $$M | sed -E -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/-(py2\.)*py3-.*whl//g' -e 's/-/\*/g') ; \
+			fi; \
+		done; \
 		if [[ $$M =~ .*pymssql.* ]]; then \
 			if [ `uname -m` = 'armv7l' ]; then \
 				export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1 \
@@ -155,7 +186,7 @@ build:
 		elif [[ $$M =~ .*tomli.* ]]; then \
 			( \
 				cd src && \
-				( tar zxvf $$M || : ) && \
+				( tar zxf $$M  --no-same-owner || : ) && \
 				cd ./tomli-*/ && \
 				python3 -c 'from setuptools import setup; setup(name="tomli", packages=["tomli"], package_data={"": ["*"]}, version="1.2.3")' bdist_wheel; \
 			); \
@@ -181,6 +212,15 @@ skel:
 clean:
 	rm -rf dest
 	rm -rf wheels
+
+check_files:
+	@echo "list of for orphaned source files:"
+	@for F in $$(ls -1 src/*); do \
+		F=$$(echo $$F | sed -e 's%src/%%'); \
+		if ! grep $$F Makefile >/dev/null 2>&1; then \
+			echo $$F; \
+		fi; \
+	done
 
 upstream:
 	set -e ; cd src && \
