python: update urllib3
pip-audit reports:

    Name    Version ID             Fix Versions
    ------- ------- -------------- ------------
    urllib3 2.6.1   CVE-2026-21441 2.6.3

diff --git a/packages/python-modules/Makefile b/packages/python-modules/Makefile
--- a/packages/python-modules/Makefile
+++ b/packages/python-modules/Makefile
@@ -127,7 +127,7 @@ endif
 ifeq ($(HAS_PYTHON_312_OR_NEWER),true)
 OVERRIDES += setuptools-80.9.0.tar.gz
 OVERRIDES += wheel-0.44.0.tar.gz
-OVERRIDES += pip-25.3.tar.gz
+OVERRIDES += pip-25.3-py3-none-any.whl
 OVERRIDES += packaging-25.0-py3-none-any.whl
 
 OVERRIDES += setuptools_scm-8.1.0.tar.gz
@@ -138,7 +138,7 @@ OVERRIDES += pymssql-2.3.1.tar.gz
 OVERRIDES += paramiko-3.5.0.tar.gz
 
 OVERRIDES += requests-2.32.5-py3-none-any.whl
-OVERRIDES += urllib3-2.6.1-py3-none-any.whl
+OVERRIDES += urllib3-2.6.3-py3-none-any.whl
 OVERRIDES += mysql_connector_python-9.5.0-py2.py3-none-any.whl
 OVERRIDES += idna-3.11-py3-none-any.whl
 endif
@@ -246,7 +246,13 @@ check_files:
 	@for F in $$(ls -1 src/*); do \
 		F=$$(echo $$F | sed -e 's%src/%%'); \
 		if ! grep $$F Makefile >/dev/null 2>&1; then \
-			echo $$F; \
+			echo "- orphaned: $$F"; \
+		fi; \
+	done
+	@echo "list of for referenced source files:"
+	@for F in $$(grep -P '^(BASE|MODULES|OVERRIDES)' Makefile | awk '{ print $$3 }' | grep -v ^$$); do \
+		if ! test -e src/$$F >/dev/null 2>&1; then \
+			echo "- missing: $$F"; \
 		fi; \
 	done
 
