Gearmand: update 1.1.18

diff --git a/packages/gearmand/skel/etc/init.d/gearmand b/packages/gearmand/skel/etc/init.d/gearmand
--- a/packages/gearmand/skel/etc/init.d/gearmand
+++ b/packages/gearmand/skel/etc/init.d/gearmand
@@ -19,7 +19,7 @@ fi
 
 NAME=gearmand
 DAEMON="$OMD_ROOT/version/sbin/gearmand"
-OPTIONS="--daemon --worker-wakeup=10 --retention-file=$OMD_ROOT/var/gearmand.retention -q retention"
+OPTIONS="--daemon -q libsqlite3 --libsqlite3-db=$OMD_ROOT/var/gearmand.db --store-queue-on-shutdown"
 PORT=`echo $CONFIG_GEARMAND_PORT | awk -F: {'print $2'}`
 LISTEN=`echo $CONFIG_GEARMAND_PORT | awk -F: {'print $1'}`
 PIDFILE=$OMD_ROOT/tmp/run/gearmand.pid
@@ -116,22 +116,20 @@ case "$1" in
         if [ -z "$pid" ]; then
             echo ". Not running."
         else
+            kill -TERM $pid
             # do a shutdown
-            if [ ! -z $NC ]; then
-                echo "shutdown" | $NC -w 1 ${LISTEN:-127.0.0.1} $PORT > /dev/null
-                x=$( expr $SHUTDOWN_TIME \* 10 )
-                while [ $x -gt 0 ]; do
-                    [ $((x%5)) -eq 0 ] && printf "."
-                    ps -p $pid > /dev/null 2>&1 && sleep 0.1 || x=0;
-                    x=$( expr $x - 1 )
-                done
+            x=$( expr $SHUTDOWN_TIME \* 10 )
+            while [ $x -gt 0 ]; do
+                [ $((x%5)) -eq 0 ] && printf "."
+                ps -p $pid > /dev/null 2>&1 && sleep 0.1 || x=0;
+                x=$( expr $x - 1 )
+            done
 
-                if ! ps -p $pid > /dev/null 2>&1 ; then
-                    echo "OK"
-                    exit 0;
-                else
-                    echo "failed"
-                fi
+            if ! ps -p $pid > /dev/null 2>&1 ; then
+                echo "OK"
+                exit 0;
+            else
+                echo "failed"
             fi
 
             # kill if still running
