add grafana rc script, sample config and hooks

diff --git a/packages/grafana/skel/etc/init.d/grafana b/packages/grafana/skel/etc/init.d/grafana
--- a/packages/grafana/skel/etc/init.d/grafana
+++ b/packages/grafana/skel/etc/init.d/grafana
@@ -1,19 +1,6 @@
-#! /usr/bin/env bash
+#!/usr/bin/env bash
 
-# chkconfig: 2345 80 05
 # description: Grafana web server & backend
-# processname: grafana
-# config: ###ROOT###/etc/grafana/defaults.ini
-# pidfile: ###ROOT###/var/run/grafana.pid
-
-### BEGIN INIT INFO
-# Provides:          grafana
-# Required-Start:    $all
-# Required-Stop:     $remote_fs $syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Start grafana at boot time
-### END INIT INFO
 
 # Check if grafana is enabled in OMD. If not terminate.
 . etc/omd/site.conf
@@ -21,121 +8,95 @@ if [ "$CONFIG_GRAFANA" != "on" ] ; then
     exit 5
 fi
 
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-NAME=grafana
-DESC="Grafana Server"
-DEFAULT=/etc/default/$NAME
-
-GRAFANA_USER=grafana
-GRAFANA_GROUP=grafana
-GRAFANA_HOME=###ROOT###/share/grafana
-CONF_DIR=###ROOT###/etc/grafana
+NAME="Grafana"
+GRAFANA_HOME=$OMD_ROOT/share/grafana
+CONF_DIR=$OMD_ROOT/etc/grafana
 WORK_DIR=$GRAFANA_HOME
-DATA_DIR=###ROOT###/var/grafana
-LOG_DIR=###ROOT###/var/log/grafana
-CONF_FILE=$CONF_DIR/defaults.ini
-MAX_OPEN_FILES=10000
-PID_FILE=###ROOT###/var/run/$NAME.pid
-DAEMON=###ROOT###/bin/$NAME
+DATA_DIR=$OMD_ROOT/var/grafana
+LOG_DIR=$OMD_ROOT/var/log/grafana
+CONF_FILE=$CONF_DIR/grafana.ini
+PID_FILE=$OMD_ROOT/tmp/run/$NAME.pid
+LOGFILE=$LOG_DIR/grafana.log
+DAEMON=$OMD_ROOT/bin/grafana
 
-if [ ! -x $DAEMON ]; then
-  echo "Program not installed or not executable"
-  exit 1
-fi
+OPTIONS="--homepath=${GRAFANA_HOME} --pidfile=${PID_FILE} --config=${CONF_FILE} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.logs=${LOG_DIR}"
 
-. /lib/lsb/init-functions
+get_status() {
+        pid=$( cat $PID_FILE 2>/dev/null )
+        if [ -n "$pid" ]; then
+            if ps -p $pid > /dev/null 2>&1 ; then
+                echo "$NAME is running with pid $pid"
+                return 0;
+            fi
+        fi
+        echo "$NAME is not running"
+        return 1;
+}
 
-if [ -r /etc/default/rcS ]; then
-	. /etc/default/rcS
-fi
-
-# overwrite settings from default file
-if [ -f "$DEFAULT" ]; then
-	. "$DEFAULT"
-fi
-
-DAEMON_OPTS="--pidfile=${PID_FILE} --config=${CONF_FILE} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.logs=${LOG_DIR}"
+stop_grafana() {
+    printf '%s' "Stopping $NAME..."
+    pid=$( cat $PID_FILE 2>/dev/null )
+    if [ -z "$pid" ]; then
+        echo ". Not running."
+    else
+        ps -p $pid > /dev/null 2>&1 && kill $pid
+        for x in 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5; do
+            printf "."
+            ps -p $pid > /dev/null 2>&1 && sleep 0.2;
+        done
+        if ! ps -p $pid > /dev/null 2>&1 ; then
+            echo "OK"
+            exit 0;
+        else
+            echo "failed"
+            exit 1;
+        fi
+    fi
+}
 
 case "$1" in
   start)
 
-	log_daemon_msg "Starting $DESC"
+        printf '%s' "Starting $NAME..."
 
-	pid=`pidofproc -p $PID_FILE grafana`
-	if [ -n "$pid" ] ; then
-		log_begin_msg "Already running."
-		log_end_msg 0
-		exit 0
-	fi
+        if get_status > /dev/null ; then
+            echo "failed"
+            echo "$NAME already running"
+            exit 0;
+        fi
 
-	# Prepare environment
-	mkdir -p "$LOG_DIR" "$DATA_DIR" && chown "$GRAFANA_USER":"$GRAFANA_GROUP" "$LOG_DIR" "$DATA_DIR"
-	touch "$PID_FILE" && chown "$GRAFANA_USER":"$GRAFANA_GROUP" "$PID_FILE"
-
-  if [ -n "$MAX_OPEN_FILES" ]; then
-		ulimit -n $MAX_OPEN_FILES
-	fi
-
-	# Start Daemon
-	start-stop-daemon --start -b --chdir "$WORK_DIR" --user "$GRAFANA_USER" -c "$GRAFANA_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS
-	return=$?
-	if [ $return -eq 0 ]
-	then
-	  sleep 1
-
-    # check if pid file has been written two
-	  if ! [[ -s $PID_FILE ]]; then
-	    log_end_msg 1
-	    exit 1
-	  fi
-
-		i=0
-		timeout=10
-		# Wait for the process to be properly started before exiting
-		until { cat "$PID_FILE" | xargs kill -0; } >/dev/null 2>&1
-		do
-			sleep 1
-			i=$(($i + 1))
-      if [ $i -gt $timeout ]; then
-			  log_end_msg 1
-			  exit 1
-			fi
-		done
-  fi
-  log_end_msg $return
+	mkdir -p "$LOG_DIR" "$DATA_DIR"
+	touch "$PID_FILE"
+        nohup $DAEMON $OPTIONS >>$LOGFILE 2>&1 &
+        if [ $? -eq 0 ]; then
+            echo "OK"
+            exit 0;
+        else
+            echo "failed"
+            exit 1;
+        fi
 	;;
   stop)
-	log_daemon_msg "Stopping $DESC"
-
-	if [ -f "$PID_FILE" ]; then
-		start-stop-daemon --stop --pidfile "$PID_FILE" \
-			--user "$GRAFANA_USER" \
-			--retry=TERM/20/KILL/5 >/dev/null
-		if [ $? -eq 1 ]; then
-			log_progress_msg "$DESC is not running but pid file exists, cleaning up"
-		elif [ $? -eq 3 ]; then
-			PID="`cat $PID_FILE`"
-			log_failure_msg "Failed to stop $DESC (pid $PID)"
-			exit 1
-		fi
-		rm -f "$PID_FILE"
-	else
-		log_progress_msg "(not running)"
-	fi
-	log_end_msg 0
+        printf '%s' "Stopping $NAME..."
+        pid=$( cat $PID_FILE 2>/dev/null )
+        if [ -z "$pid" ]; then
+            echo ". Not running."
+        else
+            stop_grafana;
+        fi
 	;;
   status)
-	status_of_proc -p $PID_FILE grafana grafana && exit 0 || exit $?
+        get_status;
+        exit $?;
     ;;
-  restart|force-reload)
-	if [ -f "$PID_FILE" ]; then
-		$0 stop
-		sleep 1
-	fi
-	$0 start
-	;;
+    reload|restart)
+        $0 stop && sleep 1 && $0 start
+        exit $?
+    ;;
   *)
-	log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
-	exit 3
-	;;
+        echo "Usage: $NAME {start|stop|kill|status|restart}"
+        exit 1
+    ;;
 esac
+
+exit 0
