grafana: enable wal for internal sqlite db
links:

- https://github.com/grafana/grafana/issues/64664
- https://github.com/grafana/grafana/issues/65115
- https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#wal
- https://sqlite.org/wal.html

diff --git a/packages/grafana/skel/etc/init.d/grafana b/packages/grafana/skel/etc/init.d/grafana
--- a/packages/grafana/skel/etc/init.d/grafana
+++ b/packages/grafana/skel/etc/init.d/grafana
@@ -35,4 +35,41 @@ START_TIMEOUT=60
 
 mkdir -p "$LOG_DIR" "$DATA_DIR"
 
+# add post hook for first start
+if ! test -s $OMD_ROOT/var/grafana/data/grafana.db; then
+    START_CALLBACK=grafana_post_start
+fi
+grafana_post_start() {
+    echo -n "first run, waiting for initial database creation"
+    for x in $(seq 600); do
+        grep -c "Completed legacy migration" $LOG_FILE >/dev/null 2>&1 && break
+        [ $((x%10)) -eq 0 ] && echo -n "."
+        PID=$(pgrep -u $OMD_SITE -o -f "$DAEMON")
+        test -n "$PID" || break # break if pid disapears
+        sleep 0.1
+    done
+    PID=$(cat $PID_FILE 2>/dev/null)
+    if [ -z "$PID" ] || ! ps -p $PID >/dev/null 2>&1; then
+        # try again once, but disable this callback
+        echo -n "trying again..."
+        START_CALLBACK=
+        rm -f $PID_FILE
+        __generic_init_wait_start
+    fi
+    for x in $(seq 600); do
+        grep -c "Completed legacy migration" $LOG_FILE >/dev/null 2>&1 && break
+        [ $((x%10)) -eq 0 ] && echo -n "."
+        PID=$(pgrep -u $OMD_SITE -o -f "$DAEMON")
+        test -n "$PID" || break # break if pid disapears
+        sleep 0.1
+    done
+    PID=$(cat $PID_FILE 2>/dev/null)
+    if [ -z "$PID" ] || ! ps -p $PID >/dev/null 2>&1; then
+        echo ""
+        echo "startup failed, see the logfile for details: $LOG_FILE"
+        exit 1
+    fi
+    grep "Completed legacy migration" $LOG_FILE >/dev/null 2>&1
+}
+
 __generic_init "$*"
